#A copy of this configuration is located in csm.cloud.dev/config/detekt-config.yml
build:
  maxIssues: 0

complexity:
  active: false
formatting:
  ArgumentListWrapping:
    active: false
  FinalNewline:
    active: false
  FunctionTypeReferenceSpacing:
    active: false
  ImportOrdering:
    active: false
  Indentation:
    active: false
  MultiLineIfElse:
    active: false
  Wrapping:
    active: false
naming:
  ClassNaming:
    excludes: [ '**/test/**' ]
performance:
  SpreadOperator:
    active: false
style:
  ForbiddenComment:
    active: false
  MagicNumber:
    active: false
  NewLineAtEndOfFile:
    active: false
  ReturnCount:
    active: false
  UnusedImports:
    active: true

