spring:
  kafka:
    consumer:
      keyDeserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      valueDeserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      enableAutoCommit: false
      group-id: "csm-monitoring-metrics-influxdb-importer-${stage}"
      properties:
        auto.offset.reset: earliest
        isolation.level: read_committed
        max.poll.records: 50
        request.timeout.ms: 20000
        session.timeout.ms: 30000
        specific.avro.reader: true
    listener:
      concurrency: 3
    properties:
      auto.register.schemas: false
      key.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
      reconnect.backoff.max.ms: 15000
      reconnect.backoff.ms: 2000
      retry.backoff.ms: 5000
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy

---
spring:
  config:
    activate:
      on-profile: kubernetes
  kafka:
    bootstrap-servers: ${kafka-broker-urls}
    properties:
      schema.registry.url: ${kafka-schemaregistry-urls}
      schema.registry.basic.auth.user.info: ${kafka-schemaregistry-api-key}:${kafka-schemaregistry-api-secret}
      basic.auth.credentials.source: 'USER_INFO'
      request.timeout.ms: 20000
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${csm-monitoring-metrics-influxdb-importer-kafka-broker-api-key}" password="${csm-monitoring-metrics-influxdb-importer-kafka-broker-api-secret}";
      sasl.mechanism: PLAIN
      security.protocol: SASL_SSL
      ssl.endpoint.identification.algorithm: https

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
