package com.bosch.pt.csm.cloud.projectmanagement.common.i18n
// ---------------------------------
// WARNING: Generated by Gradle task - NOT TO BE EDITED
// ---------------------------------

object Key {

    /**
     * en
     */
    const val KEY = "Key"

    /**
     * Weather
     */
    const val DAY_CARD_REASON_ENUM_BADWEATHER = "DayCardReasonEnum_BAD_WEATHER"

    /**
     * Client / Design change
     */
    const val DAY_CARD_REASON_ENUM_CHANGEDPRIORITY = "DayCardReasonEnum_CHANGED_PRIORITY"

    /**
     * Preliminary work not recognized
     */
    const val DAY_CARD_REASON_ENUM_CONCESSIONNOTRECOGNIZED = "DayCardReasonEnum_CONCESSION_NOT_RECOGNIZED"

    /**
     * Custom reason 1
     */
    const val DAY_CARD_REASON_ENUM_CUSTOM1 = "DayCardReasonEnum_CUSTOM1"

    /**
     * Custom reason 2
     */
    const val DAY_CARD_REASON_ENUM_CUSTOM2 = "DayCardReasonEnum_CUSTOM2"

    /**
     * Custom reason 3
     */
    const val DAY_CARD_REASON_ENUM_CUSTOM3 = "DayCardReasonEnum_CUSTOM3"

    /**
     * Custom reason 4
     */
    const val DAY_CARD_REASON_ENUM_CUSTOM4 = "DayCardReasonEnum_CUSTOM4"

    /**
     * Delayed / Defective materials
     */
    const val DAY_CARD_REASON_ENUM_DELAYEDMATERIAL = "DayCardReasonEnum_DELAYED_MATERIAL"

    /**
     * Worker shortage
     */
    const val DAY_CARD_REASON_ENUM_MANPOWERSHORTAGE = "DayCardReasonEnum_MANPOWER_SHORTAGE"

    /**
     * Missing / Incomplete information
     */
    const val DAY_CARD_REASON_ENUM_MISSINGINFOS = "DayCardReasonEnum_MISSING_INFOS"

    /**
     * Missing / Defective tools
     */
    const val DAY_CARD_REASON_ENUM_MISSINGTOOLS = "DayCardReasonEnum_MISSING_TOOLS"

    /**
     * Preliminary work not done
     */
    const val DAY_CARD_REASON_ENUM_NOCONCESSION = "DayCardReasonEnum_NO_CONCESSION"

    /**
     * Overestimation of own performance
     */
    const val DAY_CARD_REASON_ENUM_OVERESTIMATION = "DayCardReasonEnum_OVERESTIMATION"

    /**
     * Rework required
     */
    const val DAY_CARD_REASON_ENUM_TOUCHUP = "DayCardReasonEnum_TOUCHUP"

    /**
     * Accepted
     */
    const val DAY_CARD_STATUS_ENUM_APPROVED = "DayCardStatusEnum_APPROVED"

    /**
     * Done
     */
    const val DAY_CARD_STATUS_ENUM_DONE = "DayCardStatusEnum_DONE"

    /**
     * Not done
     */
    const val DAY_CARD_STATUS_ENUM_NOTDONE = "DayCardStatusEnum_NOTDONE"

    /**
     * Open
     */
    const val DAY_CARD_STATUS_ENUM_OPEN = "DayCardStatusEnum_OPEN"

    /**
     * Done
     */
    const val TASK_STATUS_ENUM_CLOSED = "TaskStatusEnum_CLOSED"

    /**
     * Draft
     */
    const val TASK_STATUS_ENUM_DRAFT = "TaskStatusEnum_DRAFT"

    /**
     * Open
     */
    const val TASK_STATUS_ENUM_OPEN = "TaskStatusEnum_OPEN"

    /**
     * Accepted
     */
    const val TASK_STATUS_ENUM_ACCEPTED = "TaskStatusEnum_ACCEPTED"

    /**
     * In Progress
     */
    const val TASK_STATUS_ENUM_STARTED = "TaskStatusEnum_STARTED"

    /**
     * workers
     */
    const val DAY_CARD_ATTRIBUTE_MANPOWER = "DayCard_Attribute_Manpower"

    /**
     * notes
     */
    const val DAY_CARD_ATTRIBUTE_NOTES = "DayCard_Attribute_Notes"

    /**
     * title
     */
    const val DAY_CARD_ATTRIBUTE_TITLE = "DayCard_Attribute_Title"

    /**
     * attachment
     */
    const val TASK_ATTRIBUTE_ATTACHMENT = "Task_Attribute_Attachment"

    /**
     * attachments
     */
    const val TASK_ATTRIBUTE_ATTACHMENTS = "Task_Attribute_Attachments"

    /**
     * discipline
     */
    const val TASK_ATTRIBUTE_CRAFT = "Task_Attribute_Craft"

    /**
     * description
     */
    const val TASK_ATTRIBUTE_DESCRIPTION = "Task_Attribute_Description"

    /**
     * location
     */
    const val TASK_ATTRIBUTE_LOCATION = "Task_Attribute_Location"

    /**
     * task title
     */
    const val TASK_ATTRIBUTE_NAME = "Task_Attribute_Name"

    /**
     * working area
     */
    const val TASK_ATTRIBUTE_WORK_AREA = "Task_Attribute_Work_Area"

    /**
     * end date
     */
    const val TASK_SCHEDULE_ATTRIBUTE_END = "Task_Schedule_Attribute_End"

    /**
     * start date
     */
    const val TASK_SCHEDULE_ATTRIBUTE_START = "Task_Schedule_Attribute_Start"

    /**
     * ${attribute} removed
     */
    const val NOTIFICATION_DETAILS_ATTRIBUTE_REMOVED = "Notification_Details_Attribute_Removed"

    /**
     * Status "${status}"
     */
    const val NOTIFICATION_DETAILS_DAY_CARD_STATUS_UPDATED = "Notification_Details_Day_Card_Status_Updated"

    /**
     * Status "${status}: ${reason}"
     */
    const val NOTIFICATION_DETAILS_DAY_CARD_STATUS_UPDATED_WITH_REASON = "Notification_Details_Day_Card_Status_Updated_With_Reason"

    /**
     * ${number} attachments added
     */
    const val NOTIFICATION_DETAILS_TASK_ATTACHMENT_ADDED_MULTIPLE = "Notification_Details_Task_Attachment_Added_Multiple"

    /**
     * 1 attachment added
     */
    const val NOTIFICATION_DETAILS_TASK_ATTACHMENT_ADDED_SINGLE = "Notification_Details_Task_Attachment_Added_Single"

    /**
     * Status "${status}"
     */
    const val NOTIFICATION_DETAILS_TASK_STATUS_UPDATED = "Notification_Details_Task_Status_Updated"

    /**
     * Status "Open"
     */
    const val NOTIFICATION_DETAILS_TASK_STATUS_RESET = "Notification_Details_Task_Status_Reset"

    /**
     * ${originator} commented on a topic
     */
    const val NOTIFICATION_SUMMARY_COMMENT_CREATED = "Notification_Summary_Comment_Created"

    /**
     * ${originator} created a day card
     */
    const val NOTIFICATION_SUMMARY_DAY_CARD_CREATED = "Notification_Summary_Day_Card_Created"

    /**
     * ${originator} updated a day card
     */
    const val NOTIFICATION_SUMMARY_DAY_CARD_UPDATED = "Notification_Summary_Day_Card_Updated"

    /**
     * ${originator} assigned a task to ${assignee}
     */
    const val NOTIFICATION_SUMMARY_TASK_ASSIGNED = "Notification_Summary_Task_Assigned"

    /**
     * ${originator} assigned a task to you
     */
    const val NOTIFICATION_SUMMARY_TASK_ASSIGNED_TO_YOU = "Notification_Summary_Task_Assigned_To_You"

    /**
     * ${originator} removed this task from your assignments
     */
    const val NOTIFICATION_SUMMARY_UNASSIGNED_TASK_FROM_YOU = "Notification_Summary_Unassigned_Task_From_You"

    /**
     * ${originator} updated a task
     */
    const val NOTIFICATION_SUMMARY_TASK_UPDATED = "Notification_Summary_Task_Updated"

    /**
     * ${originator} reset a task
     */
    const val NOTIFICATION_SUMMARY_TASK_RESET = "Notification_Summary_Task_Reset"

    /**
     * ${originator} posted a topic
     */
    const val NOTIFICATION_SUMMARY_TOPIC_CREATED = "Notification_Summary_Topic_Created"

    /**
     * [Deleted User]
     */
    const val USER_DELETED = "User_Deleted"

    /**
     * <Deleted Task>
     */
    const val DELETED_TASK = "DeletedTask"

    /**
     * and
     */
    const val MULTIPLE_ATTRIBUTE_CHANGES_SEPARATOR = "Multiple_Attribute_Changes_Separator"

    /**
     * The notification was not found.
     */
    const val ERROR_MESSAGE_NOTIFICATION_NOT_FOUND = "Error_Message_Notification_Not_Found"

}
