spring:
  config:
    activate:
      on-profile: local || kubernetes
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
      auto-commit: false
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 120000
      max-lifetime: 840000
      connectionInitSql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

---
spring:
  config:
    activate:
      on-profile: kubernetes
  datasource:
    url: ${mysql-flexible-url}

---
spring:
  config:
    activate:
      on-profile: local-user
  datasource:
    url: jdbc:mysql://localhost:3306/csm-user?user=smartsite&password=smartsite&useSSL=false&log=true&permitMysqlScheme&allowPublicKeyRetrieval

---
spring:
  config:
    activate:
      on-profile: local-company
  datasource:
    url: jdbc:mysql://localhost:3306/csm-company?user=smartsite&password=smartsite&useSSL=false&log=true&permitMysqlScheme&allowPublicKeyRetrieval

---
spring:
  config:
    activate:
      on-profile: local-project
  datasource:
    url: jdbc:mysql://localhost:3306/csm-project?user=smartsite&password=smartsite&useSSL=false&log=true&permitMysqlScheme&allowPublicKeyRetrieval

---
spring:
  config:
    activate:
      on-profile: local-featuretoggle
  datasource:
    url: jdbc:mysql://localhost:3306/csm-featuretoggle?user=smartsite&password=smartsite&useSSL=false&permitMysqlScheme&allowPublicKeyRetrieval
