apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    chart: {{ .Chart.Name }}
    chartVersion: {{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ .Chart.Name }}
    spring-boot-prometheus: enabled
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: web
    port: 8080
