apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Chart.Name }}-env-aks-kv"
spec:
  provider: azure
  parameters:
    keyvaultName: "ptcsm{{ .Values.env }}envakskv"
    objects: |
      array:
        - |
          objectName: csm-cloud-quarantine-storage-account-connection-string
          objectAlias: storage-connectionstring
          objectType: secret
        - |
          objectName: csm-cloud-storage-event-kafka-broker-api-key
          objectAlias: kafka-broker-api-key
          objectType: secret
        - |
          objectName: csm-cloud-storage-event-kafka-broker-api-secret
          objectAlias: kafka-broker-api-secret
          objectType: secret
        - |
          objectName: kafka-broker-urls
          objectType: secret
        - |
          objectName: kafka-schemaregistry-api-key
          objectType: secret
        - |
          objectName: kafka-schemaregistry-api-secret
          objectType: secret
        - |
          objectName: kafka-schemaregistry-urls
          objectType: secret
        - |
          objectName: kafka-topic-storage-event
          objectAlias: kafka-topic-upload-name
          objectType: secret
    resourceGroup: "pt-csm-{{ .Values.env }}-env-aks-kv"
    subscriptionId: {{ quote .Values.subscriptionid }}
    tenantId: {{ quote .Values.tenantid }}
