apiVersion: 1

datasources:
- name: timescaledb
  type: postgres
  url: timescaledb:5432
  user: postgres
  secureJsonData:
    password: 'smartsite'
  database: bam
  editable: true
  isDefault: true
  jsonData:
   sslmode: disable
   timescaledb: true
   postgresVersion: 1300
