package com.bosch.pt.csm.cloud.projectmanagement.common.translation
// ---------------------------------
// WARNING: Generated by Gradle task - NOT TO BE EDITED
// ---------------------------------

object Key {

    /**
     * en
     */
    const val KEY = "Key"

    /**
     * Friday
     */
    const val DAY_ENUM_FRIDAY = "DayEnum_FRIDAY"

    /**
     * Monday
     */
    const val DAY_ENUM_MONDAY = "DayEnum_MONDAY"

    /**
     * Saturday
     */
    const val DAY_ENUM_SATURDAY = "DayEnum_SATURDAY"

    /**
     * Sunday
     */
    const val DAY_ENUM_SUNDAY = "DayEnum_SUNDAY"

    /**
     * Thursday
     */
    const val DAY_ENUM_THURSDAY = "DayEnum_THURSDAY"

    /**
     * Tuesday
     */
    const val DAY_ENUM_TUESDAY = "DayEnum_TUESDAY"

    /**
     * Wednesday
     */
    const val DAY_ENUM_WEDNESDAY = "DayEnum_WEDNESDAY"

    /**
     * Weather
     */
    const val DAY_CARD_REASON_ENUM_BADWEATHER = "DayCardReasonEnum_BAD_WEATHER"

    /**
     * Client / Design change
     */
    const val DAY_CARD_REASON_ENUM_CHANGEDPRIORITY = "DayCardReasonEnum_CHANGED_PRIORITY"

    /**
     * Preliminary work not recognized
     */
    const val DAY_CARD_REASON_ENUM_CONCESSIONNOTRECOGNIZED = "DayCardReasonEnum_CONCESSION_NOT_RECOGNIZED"

    /**
     * Custom reason 1
     */
    const val DAY_CARD_REASON_ENUM_CUSTOM1 = "DayCardReasonEnum_CUSTOM1"

    /**
     * Custom reason 2
     */
    const val DAY_CARD_REASON_ENUM_CUSTOM2 = "DayCardReasonEnum_CUSTOM2"

    /**
     * Custom reason 3
     */
    const val DAY_CARD_REASON_ENUM_CUSTOM3 = "DayCardReasonEnum_CUSTOM3"

    /**
     * Custom reason 4
     */
    const val DAY_CARD_REASON_ENUM_CUSTOM4 = "DayCardReasonEnum_CUSTOM4"

    /**
     * Delayed / Defective materials
     */
    const val DAY_CARD_REASON_ENUM_DELAYEDMATERIAL = "DayCardReasonEnum_DELAYED_MATERIAL"

    /**
     * Worker shortage
     */
    const val DAY_CARD_REASON_ENUM_MANPOWERSHORTAGE = "DayCardReasonEnum_MANPOWER_SHORTAGE"

    /**
     * Missing / Incomplete information
     */
    const val DAY_CARD_REASON_ENUM_MISSINGINFOS = "DayCardReasonEnum_MISSING_INFOS"

    /**
     * Missing / Defective tools
     */
    const val DAY_CARD_REASON_ENUM_MISSINGTOOLS = "DayCardReasonEnum_MISSING_TOOLS"

    /**
     * Preliminary work not done
     */
    const val DAY_CARD_REASON_ENUM_NOCONCESSION = "DayCardReasonEnum_NO_CONCESSION"

    /**
     * Overestimation of own performance
     */
    const val DAY_CARD_REASON_ENUM_OVERESTIMATION = "DayCardReasonEnum_OVERESTIMATION"

    /**
     * Rework required
     */
    const val DAY_CARD_REASON_ENUM_TOUCHUP = "DayCardReasonEnum_TOUCHUP"

    /**
     * Accepted
     */
    const val DAY_CARD_STATUS_ENUM_APPROVED = "DayCardStatusEnum_APPROVED"

    /**
     * Done
     */
    const val DAY_CARD_STATUS_ENUM_DONE = "DayCardStatusEnum_DONE"

    /**
     * Not done
     */
    const val DAY_CARD_STATUS_ENUM_NOTDONE = "DayCardStatusEnum_NOTDONE"

    /**
     * Open
     */
    const val DAY_CARD_STATUS_ENUM_OPEN = "DayCardStatusEnum_OPEN"

    /**
     * Discipline
     */
    const val MILESTONE_TYPE_ENUM_CRAFT = "MilestoneTypeEnum_CRAFT"

    /**
     * Client
     */
    const val MILESTONE_TYPE_ENUM_INVESTOR = "MilestoneTypeEnum_INVESTOR"

    /**
     * Project
     */
    const val MILESTONE_TYPE_ENUM_PROJECT = "MilestoneTypeEnum_PROJECT"

    /**
     * Company Representative
     */
    const val PARTICIPANT_ROLE_ENUM_CR = "ParticipantRoleEnum_CR"

    /**
     * Superintendent
     */
    const val PARTICIPANT_ROLE_ENUM_CSM = "ParticipantRoleEnum_CSM"

    /**
     * Foreman
     */
    const val PARTICIPANT_ROLE_ENUM_FM = "ParticipantRoleEnum_FM"

    /**
     * Active
     */
    const val PARTICIPANT_STATUS_ENUM_ACTIVE = "ParticipantStatusEnum_ACTIVE"

    /**
     * Inactive
     */
    const val PARTICIPANT_STATUS_ENUM_INACTIVE = "ParticipantStatusEnum_INACTIVE"

    /**
     * PAT expired
     */
    const val PAT_EXPIRED = "PatExpired"

    /**
     * Assistant
     */
    const val PHONE_NUMBER_TYPE_ENUM_ASSISTANT = "PhoneNumberTypeEnum_ASSISTANT"

    /**
     * Business
     */
    const val PHONE_NUMBER_TYPE_ENUM_BUSINESS = "PhoneNumberTypeEnum_BUSINESS"

    /**
     * Fax
     */
    const val PHONE_NUMBER_TYPE_ENUM_FAX = "PhoneNumberTypeEnum_FAX"

    /**
     * Home
     */
    const val PHONE_NUMBER_TYPE_ENUM_HOME = "PhoneNumberTypeEnum_HOME"

    /**
     * Mobile
     */
    const val PHONE_NUMBER_TYPE_ENUM_MOBILE = "PhoneNumberTypeEnum_MOBILE"

    /**
     * Organization
     */
    const val PHONE_NUMBER_TYPE_ENUM_ORGANIZATION = "PhoneNumberTypeEnum_ORGANIZATION"

    /**
     * Other
     */
    const val PHONE_NUMBER_TYPE_ENUM_OTHER = "PhoneNumberTypeEnum_OTHER"

    /**
     * Pager
     */
    const val PHONE_NUMBER_TYPE_ENUM_PAGER = "PhoneNumberTypeEnum_PAGER"

    /**
     * New Building
     */
    const val PROJECT_CATEGORY_ENUM_NB = "ProjectCategoryEnum_NB"

    /**
     * Renovation
     */
    const val PROJECT_CATEGORY_ENUM_OB = "ProjectCategoryEnum_OB"

    /**
     * Reconstruction
     */
    const val PROJECT_CATEGORY_ENUM_RB = "ProjectCategoryEnum_RB"

    /**
     * Finish-to-Start
     */
    const val RELATION_TYPE_ENUM_FINISHTOSTART = "RelationTypeEnum_FINISH_TO_START"

    /**
     * Part-of
     */
    const val RELATION_TYPE_ENUM_PARTOF = "RelationTypeEnum_PART_OF"

    /**
     * Clarification needed
     */
    const val TASK_CONSTRAINT_ENUM_COMMONUNDERSTANDING = "TaskConstraintEnum_COMMON_UNDERSTANDING"

    /**
     * Custom constraint 1
     */
    const val TASK_CONSTRAINT_ENUM_CUSTOM1 = "TaskConstraintEnum_CUSTOM1"

    /**
     * Custom constraint 2
     */
    const val TASK_CONSTRAINT_ENUM_CUSTOM2 = "TaskConstraintEnum_CUSTOM2"

    /**
     * Custom constraint 3
     */
    const val TASK_CONSTRAINT_ENUM_CUSTOM3 = "TaskConstraintEnum_CUSTOM3"

    /**
     * Custom constraint 4
     */
    const val TASK_CONSTRAINT_ENUM_CUSTOM4 = "TaskConstraintEnum_CUSTOM4"

    /**
     * Equipment
     */
    const val TASK_CONSTRAINT_ENUM_EQUIPMENT = "TaskConstraintEnum_EQUIPMENT"

    /**
     * External factors
     */
    const val TASK_CONSTRAINT_ENUM_EXTERNALFACTORS = "TaskConstraintEnum_EXTERNAL_FACTORS"

    /**
     * Information
     */
    const val TASK_CONSTRAINT_ENUM_INFORMATION = "TaskConstraintEnum_INFORMATION"

    /**
     * Material
     */
    const val TASK_CONSTRAINT_ENUM_MATERIAL = "TaskConstraintEnum_MATERIAL"

    /**
     * Preliminary work
     */
    const val TASK_CONSTRAINT_ENUM_PRELIMINARYWORK = "TaskConstraintEnum_PRELIMINARY_WORK"

    /**
     * Labor
     */
    const val TASK_CONSTRAINT_ENUM_RESOURCES = "TaskConstraintEnum_RESOURCES"

    /**
     * Safety
     */
    const val TASK_CONSTRAINT_ENUM_SAFEWORKINGENVIRONMENT = "TaskConstraintEnum_SAFE_WORKING_ENVIRONMENT"

    /**
     * Accepted
     */
    const val TASK_STATUS_ENUM_ACCEPTED = "TaskStatusEnum_ACCEPTED"

    /**
     * Done
     */
    const val TASK_STATUS_ENUM_CLOSED = "TaskStatusEnum_CLOSED"

    /**
     * Draft
     */
    const val TASK_STATUS_ENUM_DRAFT = "TaskStatusEnum_DRAFT"

    /**
     * Open
     */
    const val TASK_STATUS_ENUM_OPEN = "TaskStatusEnum_OPEN"

    /**
     * In Progress
     */
    const val TASK_STATUS_ENUM_STARTED = "TaskStatusEnum_STARTED"

    /**
     * Critical
     */
    const val TOPIC_CRITICALITY_ENUM_CRITICAL = "TopicCriticalityEnum_CRITICAL"

    /**
     * Uncritical
     */
    const val TOPIC_CRITICALITY_ENUM_UNCRITICAL = "TopicCriticalityEnum_UNCRITICAL"

}
