apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Chart.Name }}-env-aks-kv"
spec:
  provider: azure
  parameters:
    keyvaultName: "ptcsm{{ .Values.env }}envakskv"
    objects: |
      array:
        - |
          objectName: csm-cloud-project-api-timeseries-kafka-broker-api-key
          objectType: secret
        - |
          objectName: csm-cloud-project-api-timeseries-kafka-broker-api-secret
          objectType: secret
        - |
          objectName: csm-cloud-project-api-timeseries-mongodbatlas-connection-string
          objectType: secret
        - |
          objectName: kafka-broker-urls
          objectType: secret
        - |
          objectName: kafka-schemaregistry-api-key
          objectType: secret
        - |
          objectName: kafka-schemaregistry-api-secret
          objectType: secret
        - |
          objectName: kafka-schemaregistry-urls
          objectType: secret
        - |
          objectName: kafka-topic-company
          objectType: secret
        - |
          objectName: kafka-topic-pat
          objectType: secret
        - |
          objectName: kafka-topic-project
          objectType: secret
        - |
          objectName: kafka-topic-user
          objectType: secret
    resourceGroup: "pt-csm-{{ .Values.env }}-env-aks-kv"
    subscriptionId: {{ quote .Values.subscriptionid }}
    tenantId: {{ quote .Values.tenantid }}
