apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Chart.Name }}-env-aks-kv"
spec:
  provider: azure
  parameters:
    keyvaultName: "ptcsm{{ .Values.env }}envakskv"
    objects: |
      array:
        - |
          objectName: csm-cloud-user-kafka-connector-kafka-broker-api-key
          objectAlias: kafka-broker-api-key
          objectType: secret
        - |
          objectName: csm-cloud-user-kafka-connector-kafka-broker-api-secret
          objectAlias: kafka-broker-api-secret
          objectType: secret
        - |
          objectName: csm-cloud-user-mysql-flexible-url
          objectAlias: mysql-flexible-url
          objectType: secret
        - |
          objectName: kafka-broker-urls
          objectType: secret
        - |
          objectName: kafka-topic-consents
          objectType: secret
        - |
          objectName: kafka-topic-craft
          objectType: secret
        - |
          objectName: kafka-topic-pat
          objectType: secret
        - |
          objectName: kafka-topic-user
          objectType: secret
    resourceGroup: "pt-csm-{{ .Values.env }}-env-aks-kv"
    subscriptionId: {{ quote .Values.subscriptionid }}
    tenantId: {{ quote .Values.tenantid }}
