# Environment specific values for csm-cloud-project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

domainName: sandbox2.bosch-refinemysite.com
domainNameAdmin: sandbox2-admin.bosch-refinemysite.com
domainNameApi: sandbox2-api.bosch-refinemysite.com
profiles: staging-open

# configuration for KV Flex volumes
env: sandbox2
subscription: sandbox
subscriptionid: "REPLACE_ME"
tenantid: "REPLACE_ME"
