package com.bosch.pt.csm.cloud.projectmanagement.common.i18n
// ---------------------------------
// WARNING: Generated by Gradle task - NOT TO BE EDITED
// ---------------------------------

object Key {

    /**
     * en
     */
    const val KEY = "Key"

    /**
     * Clarification needed
     */
    const val TASK_ACTION_ENUM_COMMONUNDERSTANDING = "TaskActionEnum_COMMON_UNDERSTANDING"

    /**
     * Equipment
     */
    const val TASK_ACTION_ENUM_EQUIPMENT = "TaskActionEnum_EQUIPMENT"

    /**
     * External factors
     */
    const val TASK_ACTION_ENUM_EXTERNALFACTORS = "TaskActionEnum_EXTERNAL_FACTORS"

    /**
     * Information
     */
    const val TASK_ACTION_ENUM_INFORMATION = "TaskActionEnum_INFORMATION"

    /**
     * Material
     */
    const val TASK_ACTION_ENUM_MATERIAL = "TaskActionEnum_MATERIAL"

    /**
     * Preliminary work
     */
    const val TASK_ACTION_ENUM_PRELIMINARYWORK = "TaskActionEnum_PRELIMINARY_WORK"

    /**
     * Labor
     */
    const val TASK_ACTION_ENUM_RESOURCES = "TaskActionEnum_RESOURCES"

    /**
     * Safety
     */
    const val TASK_ACTION_ENUM_SAFEWORKINGENVIRONMENT = "TaskActionEnum_SAFE_WORKING_ENVIRONMENT"

    /**
     * Clarification needed
     */
    const val TASK_CONSTRAINT_ENUM_COMMONUNDERSTANDING = "TaskConstraintEnum_COMMON_UNDERSTANDING"

    /**
     * Equipment
     */
    const val TASK_CONSTRAINT_ENUM_EQUIPMENT = "TaskConstraintEnum_EQUIPMENT"

    /**
     * External factors
     */
    const val TASK_CONSTRAINT_ENUM_EXTERNALFACTORS = "TaskConstraintEnum_EXTERNAL_FACTORS"

    /**
     * Information
     */
    const val TASK_CONSTRAINT_ENUM_INFORMATION = "TaskConstraintEnum_INFORMATION"

    /**
     * Material
     */
    const val TASK_CONSTRAINT_ENUM_MATERIAL = "TaskConstraintEnum_MATERIAL"

    /**
     * Preliminary work
     */
    const val TASK_CONSTRAINT_ENUM_PRELIMINARYWORK = "TaskConstraintEnum_PRELIMINARY_WORK"

    /**
     * Labor
     */
    const val TASK_CONSTRAINT_ENUM_RESOURCES = "TaskConstraintEnum_RESOURCES"

    /**
     * Safety
     */
    const val TASK_CONSTRAINT_ENUM_SAFEWORKINGENVIRONMENT = "TaskConstraintEnum_SAFE_WORKING_ENVIRONMENT"

    /**
     * Custom constraint 1
     */
    const val TASK_CONSTRAINT_ENUM_CUSTOM1 = "TaskConstraintEnum_CUSTOM1"

    /**
     * Custom constraint 2
     */
    const val TASK_CONSTRAINT_ENUM_CUSTOM2 = "TaskConstraintEnum_CUSTOM2"

    /**
     * Custom constraint 3
     */
    const val TASK_CONSTRAINT_ENUM_CUSTOM3 = "TaskConstraintEnum_CUSTOM3"

    /**
     * Custom constraint 4
     */
    const val TASK_CONSTRAINT_ENUM_CUSTOM4 = "TaskConstraintEnum_CUSTOM4"

    /**
     * Weather
     */
    const val DAY_CARD_REASON_ENUM_BADWEATHER = "DayCardReasonEnum_BAD_WEATHER"

    /**
     * Client / Design change
     */
    const val DAY_CARD_REASON_ENUM_CHANGEDPRIORITY = "DayCardReasonEnum_CHANGED_PRIORITY"

    /**
     * Preliminary work not recognized
     */
    const val DAY_CARD_REASON_ENUM_CONCESSIONNOTRECOGNIZED = "DayCardReasonEnum_CONCESSION_NOT_RECOGNIZED"

    /**
     * Custom reason 1
     */
    const val DAY_CARD_REASON_ENUM_CUSTOM1 = "DayCardReasonEnum_CUSTOM1"

    /**
     * Custom reason 2
     */
    const val DAY_CARD_REASON_ENUM_CUSTOM2 = "DayCardReasonEnum_CUSTOM2"

    /**
     * Custom reason 3
     */
    const val DAY_CARD_REASON_ENUM_CUSTOM3 = "DayCardReasonEnum_CUSTOM3"

    /**
     * Custom reason 4
     */
    const val DAY_CARD_REASON_ENUM_CUSTOM4 = "DayCardReasonEnum_CUSTOM4"

    /**
     * Delayed / Defective materials
     */
    const val DAY_CARD_REASON_ENUM_DELAYEDMATERIAL = "DayCardReasonEnum_DELAYED_MATERIAL"

    /**
     * Worker shortage
     */
    const val DAY_CARD_REASON_ENUM_MANPOWERSHORTAGE = "DayCardReasonEnum_MANPOWER_SHORTAGE"

    /**
     * Missing / Incomplete information
     */
    const val DAY_CARD_REASON_ENUM_MISSINGINFOS = "DayCardReasonEnum_MISSING_INFOS"

    /**
     * Missing / Defective tools
     */
    const val DAY_CARD_REASON_ENUM_MISSINGTOOLS = "DayCardReasonEnum_MISSING_TOOLS"

    /**
     * Preliminary work not done
     */
    const val DAY_CARD_REASON_ENUM_NOCONCESSION = "DayCardReasonEnum_NO_CONCESSION"

    /**
     * Overestimation of own performance
     */
    const val DAY_CARD_REASON_ENUM_OVERESTIMATION = "DayCardReasonEnum_OVERESTIMATION"

    /**
     * Rework required
     */
    const val DAY_CARD_REASON_ENUM_TOUCHUP = "DayCardReasonEnum_TOUCHUP"

    /**
     * Given activity cannot be found.
     */
    const val ACTIVITY_VALIDATION_ERROR_NOT_FOUND = "Activity_ValidationError_NotFound"

    /**
     * The attachment wasn't found.
     */
    const val ATTACHMENT_VALIDATION_ERROR_NOT_FOUND = "Attachment_ValidationError_NotFound"

    /**
     * [Deleted User]
     */
    const val USER_DELETED = "User_Deleted"

    /**
     * Given task cannot be found.
     */
    const val TASK_VALIDATION_ERROR_NOT_FOUND = "Task_ValidationError_NotFound"

    /**
     * ${originator} assigned the task to ${assignee}
     */
    const val TASK_ACTIVITY_ASSIGNED = "TaskActivity_Assigned"

    /**
     * ${originator} removed this task from assignments of ${assignee}
     */
    const val TASK_ACTIVITY_UNASSIGNED = "TaskActivity_Unassigned"

    /**
     * ${originator} assigned the task to ${assignee}
     */
    const val TASK_ACTIVITY_REASSIGNED = "TaskActivity_Reassigned"

    /**
     * ${originator} finished the task
     */
    const val TASK_ACTIVITY_FINISHED = "TaskActivity_Finished"

    /**
     * ${originator} accepted the task
     */
    const val TASK_ACTIVITY_ACCEPTED = "TaskActivity_Accepted"

    /**
     * ${originator} created the task ${task}
     */
    const val TASK_ACTIVITY_CREATED = "TaskActivity_Created"

    /**
     * ${originator} updated ${count} attribute(s) of the task
     */
    const val TASK_ACTIVITY_UPDATED = "TaskActivity_Updated"

    /**
     * ${originator} sent the task to ${assignee}
     */
    const val TASK_ACTIVITY_SENT = "TaskActivity_Sent"

    /**
     * ${originator} sent the task
     */
    const val TASK_ACTIVITY_SENT_WITHOUT_ASSIGNEE = "TaskActivity_Sent_Without_Assignee"

    /**
     * ${originator} started the task
     */
    const val TASK_ACTIVITY_STARTED = "TaskActivity_Started"

    /**
     * ${originator} reset the task to open
     */
    const val TASK_ACTIVITY_RESET = "TaskActivity_Reset"

    /**
     * ${originator} deleted the task ${task}
     */
    const val TASK_ACTIVITY_DELETED = "TaskActivity_Deleted"

    /**
     * Set assignee to â{0}â
     */
    const val TASK_ACTIVITY_CREATED_ASSIGNEE = "TaskActivity_Created_Assignee"

    /**
     * Set title to â{0}â
     */
    const val TASK_ACTIVITY_CREATED_NAME = "TaskActivity_Created_Name"

    /**
     * Set description to â{0}â
     */
    const val TASK_ACTIVITY_CREATED_DESCRIPTION = "TaskActivity_Created_Description"

    /**
     * Set location to â{0}â
     */
    const val TASK_ACTIVITY_CREATED_LOCATION = "TaskActivity_Created_Location"

    /**
     * Set discipline to â{0}â
     */
    const val TASK_ACTIVITY_CREATED_CRAFT = "TaskActivity_Created_Craft"

    /**
     * Set state to â{0}â
     */
    const val TASK_ACTIVITY_CREATED_STATUS = "TaskActivity_Created_Status"

    /**
     * Changed assignee from â{0}â to â{1}â
     */
    const val TASK_ACTIVITY_UPDATED_ASSIGNEE = "TaskActivity_Updated_Assignee"

    /**
     * Removed assignee â{0}â
     */
    const val TASK_ACTIVITY_UPDATED_ASSIGNEE_REMOVED = "TaskActivity_Updated_Assignee_Removed"

    /**
     * Changed title from â{0}â to â{1}â
     */
    const val TASK_ACTIVITY_UPDATED_NAME = "TaskActivity_Updated_Name"

    /**
     * Set description â{0}â
     */
    const val TASK_ACTIVITY_UPDATED_DESCRIPTION = "TaskActivity_Updated_Description"

    /**
     * Removed description â{0}â
     */
    const val TASK_ACTIVITY_UPDATED_DESCRIPTION_REMOVED = "TaskActivity_Updated_Description_Removed"

    /**
     * Changed location from â{0}â to â{1}â
     */
    const val TASK_ACTIVITY_UPDATED_LOCATION = "TaskActivity_Updated_Location"

    /**
     * Set location to â{0}â
     */
    const val TASK_ACTIVITY_UPDATED_LOCATION_INITIALIZED = "TaskActivity_Updated_Location_Initialized"

    /**
     * Removed location â{0}â
     */
    const val TASK_ACTIVITY_UPDATED_LOCATION_REMOVED = "TaskActivity_Updated_Location_Removed"

    /**
     * Changed discipline from â{0}â to â{1}â
     */
    const val TASK_ACTIVITY_UPDATED_CRAFT = "TaskActivity_Updated_Craft"

    /**
     * Set state to â{0}â
     */
    const val TASK_ACTIVITY_UPDATED_STATUS = "TaskActivity_Updated_Status"

    /**
     * ${originator} created the critical topic ${topic}
     */
    const val TOPIC_ACTIVITY_CREATED_CRITICAL = "TopicActivity_Created_Critical"

    /**
     * ${originator} created a critical topic
     */
    const val TOPIC_ACTIVITY_CREATED_CRITICAL_WITHOUT_TEXT = "TopicActivity_Created_Critical_WithoutText"

    /**
     * ${originator} created the topic ${topic}
     */
    const val TOPIC_ACTIVITY_CREATED_UNCRITICAL = "TopicActivity_Created_Uncritical"

    /**
     * ${originator} created a topic
     */
    const val TOPIC_ACTIVITY_CREATED_UNCRITICAL_WITHOUT_TEXT = "TopicActivity_Created_Uncritical_WithoutText"

    /**
     * ${originator} changed the topic ${topic} to critical
     */
    const val TOPIC_ACTIVITY_ESCALATED = "TopicActivity_Escalated"

    /**
     * ${originator} changed a topic to critical
     */
    const val TOPIC_ACTIVITY_ESCALATED_WITHOUT_TEXT = "TopicActivity_Escalated_WithoutText"

    /**
     * ${originator} changed the topic ${topic} to uncritical
     */
    const val TOPIC_ACTIVITY_DEESCALATED = "TopicActivity_Deescalated"

    /**
     * ${originator} changed a topic to uncritical
     */
    const val TOPIC_ACTIVITY_DEESCALATED_WITHOUT_TEXT = "TopicActivity_Deescalated_WithoutText"

    /**
     * ${originator} deleted the topic ${topic}
     */
    const val TOPIC_ACTIVITY_DELETED = "TopicActivity_Deleted"

    /**
     * ${originator} deleted a topic
     */
    const val TOPIC_ACTIVITY_DELETED_WITHOUT_TEXT = "TopicActivity_Deleted_WithoutText"

    /**
     * ${originator} commented on the topic ${topic}
     */
    const val MESSAGE_ACTIVITY_CREATED = "MessageActivity_Created"

    /**
     * ${originator} commented on a topic
     */
    const val MESSAGE_ACTIVITY_CREATED_TOPIC_WITHOUT_TEXT = "MessageActivity_Created_TopicWithoutText"

    /**
     * ${originator} deleted the comment ${comment}
     */
    const val MESSAGE_ACTIVITY_DELETED = "MessageActivity_Deleted"

    /**
     * ${originator} removed a comment from the topic ${topic}
     */
    const val MESSAGE_ACTIVITY_DELETED_MESSAGE_WITHOUT_TEXT = "MessageActivity_Deleted_MessageWithoutText"

    /**
     * ${originator} removed a comment from a topic
     */
    const val MESSAGE_ACTIVITY_DELETED_MESSAGE_AND_TOPIC_WITHOUT_TEXT = "MessageActivity_Deleted_MessageAndTopicWithoutText"

    /**
     * ${originator} added an attachment to the task
     */
    const val TASK_ATTACHMENT_ACTIVITY_SAVED = "TaskAttachmentActivity_Saved"

    /**
     * ${originator} deleted an attachment of the task
     */
    const val TASK_ATTACHMENT_ACTIVITY_DELETED = "TaskAttachmentActivity_Deleted"

    /**
     * ${originator} added an attachment to the topic ${topic}
     */
    const val TOPIC_ATTACHMENT_ACTIVITY_SAVED = "TopicAttachmentActivity_Saved"

    /**
     * ${originator} added an attachment to a topic
     */
    const val TOPIC_ATTACHMENT_ACTIVITY_SAVED_TOPIC_WITHOUT_TEXT = "TopicAttachmentActivity_Saved_TopicWithoutText"

    /**
     * ${originator} added an attachment to the topic ${topic}
     */
    const val MESSAGE_ATTACHMENT_ACTIVITY_SAVED = "MessageAttachmentActivity_Saved"

    /**
     * ${originator} added an attachment to a topic
     */
    const val MESSAGE_ATTACHMENT_ACTIVITY_SAVED_TOPIC_WITHOUT_TEXT = "MessageAttachmentActivity_Saved_TopicWithoutText"

    /**
     * topic
     */
    const val ACTIVITY_TOPIC_DESCRIPTION = "Activity_Topic_Description"

    /**
     * message
     */
    const val ACTIVITY_MESSAGE_DESCRIPTION = "Activity_Message_Description"

    /**
     * {0}
     */
    const val BARE_PARAMETERS_ONE_PARAMETER = "BareParameters_OneParameter"

    /**
     * Set working area to â{0}â
     */
    const val TASK_ACTIVITY_CREATED_WORKAREA = "TaskActivity_Created_Workarea"

    /**
     * Changed working area from â{0}â to â{1}â
     */
    const val TASK_ACTIVITY_UPDATED_WORKAREA = "TaskActivity_Updated_Workarea"

    /**
     * Removed working area â{0}â
     */
    const val TASK_ACTIVITY_REMOVED_WORKAREA = "TaskActivity_Removed_Workarea"

    /**
     * ${originator} set the schedule
     */
    const val TASK_SCHEDULE_ACTIVITY_CREATED = "TaskScheduleActivity_Created"

    /**
     * ${originator} updated the schedule
     */
    const val TASK_SCHEDULE_ACTIVITY_UPDATED = "TaskScheduleActivity_Updated"

    /**
     * ${originator} updated the schedule
     */
    const val TASK_SCHEDULE_ACTIVITY_DELETED = "TaskScheduleActivity_Deleted"

    /**
     * Set start date to â{0}â
     */
    const val TASK_SCHEDULE_ACTIVITY_CREATED_START = "TaskScheduleActivity_Created_Start"

    /**
     * Set due date to â{0}â
     */
    const val TASK_SCHEDULE_ACTIVITY_CREATED_END = "TaskScheduleActivity_Created_End"

    /**
     * Changed start date from â{0}â to â{1}â
     */
    const val TASK_SCHEDULE_ACTIVITY_UPDATED_START = "TaskScheduleActivity_Updated_Start"

    /**
     * Changed due date from â{0}â to â{1}â
     */
    const val TASK_SCHEDULE_ACTIVITY_UPDATED_END = "TaskScheduleActivity_Updated_End"

    /**
     * Removed start date â{0}â
     */
    const val TASK_SCHEDULE_ACTIVITY_DELETED_START = "TaskScheduleActivity_Deleted_Start"

    /**
     * Removed due date â{0}â
     */
    const val TASK_SCHEDULE_ACTIVITY_DELETED_END = "TaskScheduleActivity_Deleted_End"

    /**
     * Changed date of day card â{0}â from â{1}â to â{2}â
     */
    const val TASK_SCHEDULE_ACTIVITY_UPDATED_DAY_CARD_REORDERED = "TaskScheduleActivity_Updated_DayCard_Reordered"

    /**
     * Set date of day card â{0}â to â{1}â
     */
    const val TASK_SCHEDULE_ACTIVITY_UPDATED_DAY_CARD_ADDED = "TaskScheduleActivity_Updated_DayCard_Added"

    /**
     * Removed day card â{0}â from â{1}â
     */
    const val TASK_SCHEDULE_ACTIVITY_UPDATED_DAY_CARD_REMOVED = "TaskScheduleActivity_Updated_DayCard_Removed"

    /**
     * ${originator} changed state of â${daycard}â: Accepted
     */
    const val DAY_CARD_ACTIVITY_APPROVED = "DayCardActivity_Approved"

    /**
     * ${originator} changed state of â${daycard}â: Not Done
     */
    const val DAY_CARD_ACTIVITY_CANCELLED = "DayCardActivity_Cancelled"

    /**
     * Set reason to â{0}â
     */
    const val DAY_CARD_ACTIVITY_CANCELLED_REASON = "DayCardActivity_Cancelled_Reason"

    /**
     * ${originator} changed state of â${daycard}â: Done
     */
    const val DAY_CARD_ACTIVITY_COMPLETED = "DayCardActivity_Completed"

    /**
     * ${originator} created the day card â${daycard}â
     */
    const val DAY_CARD_ACTIVITY_CREATED = "DayCardActivity_Created"

    /**
     * Set title to â{0}â
     */
    const val DAY_CARD_ACTIVITY_CREATED_TITLE = "DayCardActivity_Created_Title"

    /**
     * Set note to â{0}â
     */
    const val DAY_CARD_ACTIVITY_CREATED_NOTE = "DayCardActivity_Created_Note"

    /**
     * Set number of workers to â{0}â
     */
    const val DAY_CARD_ACTIVITY_CREATED_MANPOWER = "DayCardActivity_Created_Manpower"

    /**
     * ${originator} deleted the day card â${daycard}â
     */
    const val DAY_CARD_ACTIVITY_DELETED = "DayCardActivity_Deleted"

    /**
     * ${originator} changed state of â${daycard}â: Open
     */
    const val DAY_CARD_ACTIVITY_RESET = "DayCardActivity_Reset"

    /**
     * ${originator} updated the day card â${daycard}â
     */
    const val DAY_CARD_ACTIVITY_UPDATED = "DayCardActivity_Updated"

    /**
     * Changed number of workers from â{0}â to â{1}â
     */
    const val DAY_CARD_ACTIVITY_UPDATED_MANPOWER = "DayCardActivity_Updated_Manpower"

    /**
     * Changed note from â{0}â to â{1}â
     */
    const val DAY_CARD_ACTIVITY_UPDATED_NOTE = "DayCardActivity_Updated_Note"

    /**
     * Removed note â{0}â
     */
    const val DAY_CARD_ACTIVITY_UPDATED_NOTE_REMOVED = "DayCardActivity_Updated_Note_Removed"

    /**
     * Changed title from â{0}â to â{1}â
     */
    const val DAY_CARD_ACTIVITY_UPDATED_TITLE = "DayCardActivity_Updated_Title"

    /**
     * ${originator} added constraints
     */
    const val TASK_ACTION_SELECTION_ACTIVITY_CREATED = "TaskActionSelectionActivity_Created"

    /**
     * ${originator} added constraints
     */
    const val TASK_ACTION_SELECTION_ACTIVITY_ACTIONS_ADDED = "TaskActionSelectionActivity_ActionsAdded"

    /**
     * ${originator} removed constraints
     */
    const val TASK_ACTION_SELECTION_ACTIVITY_ACTIONS_REMOVED = "TaskActionSelectionActivity_ActionsRemoved"

    /**
     * ${originator} updated constraints
     */
    const val TASK_ACTION_SELECTION_ACTIVITY_ACTIONS_UPDATED = "TaskActionSelectionActivity_ActionsUpdated"

    /**
     * ${originator} removed constraints
     */
    const val TASK_ACTION_SELECTION_ACTIVITY_DELETED = "TaskActionSelectionActivity_Deleted"

    /**
     * Added "{0}"
     */
    const val TASK_ACTION_SELECTION_ACTIVITY_ADDED = "TaskActionSelectionActivity_Added"

    /**
     * Removed "{0}"
     */
    const val TASK_ACTION_SELECTION_ACTIVITY_REMOVED = "TaskActionSelectionActivity_Removed"

}
