logging:
  level:
    ROOT: warn
    #com.zaxxer.hikari: debug

    com.bosch.pt.csm:
      CompanyApplication: info
      CompanyApplicationKt: info
      application:
        config: info
        lifecycle: info
      # attachment.repository.AzureBlobStorageRepository: info
      cloud.common.security.CustomAuthenticationEntryPoint: info
      common.facade.listener.AbstractRestoreDbEventListener: info
      common.facade.rest.ErrorController: info
    org:
      # Configure logging for sql parameters
      # hibernate:
      #  type.descriptor.sql: TRACE
      #  SQL: DEBUG
      apache.kafka.clients.consumer.internals.Fetcher: error
      flywaydb.core.internal.command: info
      springframework:
        boot:
          context: info
          web.embedded.tomcat.GracefulShutdown: info
        cloud.config: debug
        kafka.core.KafkaAdmin: info
        retry: info
        web.filter.CommonsRequestLoggingFilter: debug
        web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: error


---
spring:
  config:
    activate:
      on-profile: log-jpa
  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        event: debug
        persister:
          collection: debug
        internal:
          util:
            EntityPrinter: debug
        type:
          EnumType: trace
          CollectionType: trace
          descriptor:
            sql: trace
      springframework:
        transaction:
          support:
            AbstractPlatformTransactionManager: debug
        orm:
          jpa:
            JpaTransactionManager: debug
---
spring:
  config:
    activate:
      on-profile: local | event-listener-debug-logs-enabled

logging:
  level:
    com.bosch.pt.csm:
      company.employee.command.eventprocessor.RemoveEmployeeOnUserDeletedEventListener: debug
      company.employee.query.employableuser.EmployableUserProjectorEventListener: debug
      company.eventstore.CompanyContextRestoreSnapshotsEventListener: debug
      user.eventstore.listener.UserEventListenerImpl: debug