# Environment specific values for csm-cloud-project-kafka-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

stage: dev

# configuration for KV Flex volumes
env: dev
subscription: dev
subscriptionid: "REPLACE_ME"
tenantid: "REPLACE_ME"
