apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Chart.Name }}-sub-aks-kv"
spec:
  provider: azure
  parameters:
    keyvaultName: "ptcsm{{ .Values.subscription }}subakskv"
    objects: |
      array:
        - |
          objectName: mailjet-api-key
          objectType: secret
        - |
          objectName: mailjet-api-secret
          objectType: secret
    resourceGroup: "pt-csm-{{ .Values.subscription }}-sub-aks-kv"
    subscriptionId: {{ quote .Values.subscriptionid }}
    tenantId: {{ quote .Values.tenantid }}
