/*
 * ************************************************************************
 *
 *  Copyright:       Robert Bosch Power Tools GmbH, 2018 - 2021
 *
 * ************************************************************************
 */

package com.bosch.pt.csm.cloud.common.model

enum class IsoCountryCodeEnum(val countryName: String, val alternativeCountryName: String) {
  AD("Andorra", "Andorra"),
  AE("United Arab Emirates", "United Arab Emirates (the)"),
  AF("Afghanistan", "Afghanistan"),
  AG("Antigua and Barbuda", "Antigua and Barbuda"),
  AI("Anguilla", "Anguilla"),
  AL("Albania", "Albania"),
  AM("Armenia", "Armenia"),
  AO("Angola", "Angola"),
  AQ("Antarctica", "Antarctica"),
  AR("Argentina", "Argentina"),
  AS("American Samoa", "American Samoa"),
  AT("Austria", "Austria"),
  AU("Australia", "Australia"),
  AW("Aruba", "Aruba"),
  AX("Åland Islands", "Åland Islands"),
  AZ("Azerbaijan", "Azerbaijan"),
  BA("Bosnia and Herzegovina", "Bosnia and Herzegovina"),
  BB("Barbados", "Barbados"),
  BD("Bangladesh", "Bangladesh"),
  BE("Belgium", "Belgium"),
  BF("Burkina Faso", "Burkina Faso"),
  BG("Bulgaria", "Bulgaria"),
  BH("Bahrain", "Bahrain"),
  BI("Burundi", "Burundi"),
  BJ("Benin", "Benin"),
  BL("Saint Barthélemy", "Saint Barthélemy"),
  BM("Bermuda", "Bermuda"),
  BN("Brunei", "Brunei Darussalam"),
  BO("Bolivia", "Bolivia (Plurinational State of)"),
  BQ("Bonaire, Sint Eustatius and Saba", "Bonaire, Sint Eustatius and Saba"),
  BR("Brazil", "Brazil"),
  BS("Bahamas", "Bahamas (the)"),
  BT("Bhutan", "Bhutan"),
  BV("Bouvet Island", "Bouvet Island"),
  BW("Botswana", "Botswana"),
  BY("Belarus", "Belarus"),
  BZ("Belize", "Belize"),
  CA("Canada", "Canada"),
  CC("Cocos Keeling Islands", "Cocos (Keeling) Islands (the)"),
  CD("Democratic Republic of the Congo", "Congo (the Democratic Republic of the)"),
  CF("Central African Republic", "Central African Republic (the)"),
  CG("Republic of the Congo", "Congo (the)"),
  CH("Switzerland", "Switzerland"),
  CI("Ivory Coast", "Côte d'Ivoire"),
  CK("Cook Islands", "Cook Islands (the)"),
  CL("Chile", "Chile"),
  CM("Cameroon", "Cameroon"),
  CN("China", "China"),
  CO("Colombia", "Colombia"),
  CR("Costa Rica", "Costa Rica"),
  CU("Cuba", "Cuba"),
  CV("Cabo Verde", "Cabo Verde"),
  CW("Curacao", "Curaçao"),
  CX("Christmas Island", "Christmas Island"),
  CY("Cyprus", "Cyprus"),
  CZ("Czechia", "Czechia"),
  DE("Germany", "Germany"),
  DJ("Djibouti", "Djibouti"),
  DK("Denmark", "Denmark"),
  DM("Dominica", "Dominica"),
  DO("Dominican Republic", "Dominican Republic (the)"),
  DZ("Algeria", "Algeria"),
  EC("Ecuador", "Ecuador"),
  EE("Estonia", "Estonia"),
  EG("Egypt", "Egypt"),
  EH("Western Sahara", "Western Sahara"),
  ER("Eritrea", "Eritrea"),
  ES("Spain", "Spain"),
  ET("Ethiopia", "Ethiopia"),
  FI("Finland", "Finland"),
  FJ("Fiji", "Fiji"),
  FK("Falkland Islands", "Falkland Islands (the) [Malvinas]"),
  FM("Federated States of Micronesia", "Micronesia (Federated States of)"),
  FO("Faroe Islands", "Faroe Islands (the)"),
  FR("France", "France"),
  GA("Gabon", "Gabon"),
  GB("United Kingdom", "United Kingdom of Great Britain and Northern Ireland (the)"),
  GD("Grenada", "Grenada"),
  GE("Georgia", "Georgia"),
  GF("French Guiana", "French Guiana"),
  GG("Guernsey", "Guernsey"),
  GH("Ghana", "Ghana"),
  GI("Gibraltar", "Gibraltar"),
  GL("Greenland", "Greenland"),
  GM("The Gambia", "Gambia (the)"),
  GN("Guinea", "Guinea"),
  GP("Guadeloupe", "Guadeloupe"),
  GQ("Equatorial Guinea", "Equatorial Guinea"),
  GR("Greece", "Greece"),
  GS("South Georgia and South Sandwich Islands", "South Georgia and the South Sandwich Islands"),
  GT("Guatemala", "Guatemala"),
  GU("Guam", "Guam"),
  GW("Guinea-Bissau", "Guinea-Bissau"),
  GY("Guyana", "Guyana"),
  HK("Hong Kong", "Hong Kong"),
  HM("Heard Island and McDonald Islands", "Heard Island and McDonald Islands"),
  HN("Honduras", "Honduras"),
  HR("Croatia", "Croatia"),
  HT("Haiti", "Haiti"),
  HU("Hungary", "Hungary"),
  ID("Indonesia", "Indonesia"),
  IE("Ireland", "Ireland"),
  IL("Israel", "Israel"),
  IM("Isle of Man", "Isle of Man"),
  IN("India", "India"),
  IO("British Indian Ocean Territory", "British Indian Ocean Territory (the)"),
  IQ("Iraq", "Iraq"),
  IR("Iran", "Iran (Islamic Republic of)"),
  IS("Iceland", "Iceland"),
  IT("Italy", "Italy"),
  JE("Jersey", "Jersey"),
  JM("Jamaica", "Jamaica"),
  JO("Jordan", "Jordan"),
  JP("Japan", "Japan"),
  KE("Kenya", "Kenya"),
  KG("Kyrgyzstan", "Kyrgyzstan"),
  KH("Cambodia", "Cambodia"),
  KI("Kiribati", "Kiribati"),
  KM("Comoros", "Comoros (the)"),
  KN("Saint Kitts and Nevis", "Saint Kitts and Nevis"),
  KP("North Korea", "Korea (the Democratic People's Republic of)"),
  KR("South Korea", "Korea (the Republic of)"),
  KW("Kuwait", "Kuwait"),
  KY("Cayman Islands", "Cayman Islands (the)"),
  KZ("Kazakhstan", "Kazakhstan"),
  LA("Laos", "Lao People's Democratic Republic (the)"),
  LB("Lebanon", "Lebanon"),
  LC("Saint Lucia", "Saint Lucia"),
  LI("Liechtenstein", "Liechtenstein"),
  LK("Sri Lanka", "Sri Lanka"),
  LR("Liberia", "Liberia"),
  LS("Lesotho", "Lesotho"),
  LT("Lithuania", "Lithuania"),
  LU("Luxembourg", "Luxembourg"),
  LV("Latvia", "Latvia"),
  LY("Libya", "Libya"),
  MA("Morocco", "Morocco"),
  MC("Monaco", "Monaco"),
  MD("Moldova", "Moldova (the Republic of)"),
  ME("Montenegro", "Montenegro"),
  MF("Saint Martin", "Saint Martin (French part)"),
  MG("Madagascar", "Madagascar"),
  MH("Marshall Islands", "Marshall Islands (the)"),
  MK("North Macedonia", "Republic of North Macedonia"),
  ML("Mali", "Mali"),
  MM("Myanmar", "Myanmar"),
  MN("Mongolia", "Mongolia"),
  MO("Macao", "Macao"),
  MP("Northern Mariana Islands", "Northern Mariana Islands (the)"),
  MQ("Martinique", "Martinique"),
  MR("Mauritania", "Mauritania"),
  MS("Montserrat", "Montserrat"),
  MT("Malta", "Malta"),
  MU("Mauritius", "Mauritius"),
  MV("Maldives", "Maldives"),
  MW("Malawi", "Malawi"),
  MX("Mexico", "Mexico"),
  MY("Malaysia", "Malaysia"),
  MZ("Mozambique", "Mozambique"),
  NA("Namibia", "Namibia"),
  NC("New Caledonia", "New Caledonia"),
  NE("Niger", "Niger (the)"),
  NF("Norfolk Island", "Norfolk Island"),
  NG("Nigeria", "Nigeria"),
  NI("Nicaragua", "Nicaragua"),
  NL("Netherlands", "Netherlands (the)"),
  NO("Norway", "Norway"),
  NP("Nepal", "Nepal"),
  NR("Nauru", "Nauru"),
  NU("Niue", "Niue"),
  NZ("New Zealand", "New Zealand"),
  OM("Oman", "Oman"),
  PA("Panama", "Panama"),
  PE("Peru", "Peru"),
  PF("French Polynesia", "French Polynesia"),
  PG("Papua New Guinea", "Papua New Guinea"),
  PH("Philippines", "Philippines (the)"),
  PK("Pakistan", "Pakistan"),
  PL("Poland", "Poland"),
  PM("Saint Pierre and Miquelon", "Saint Pierre and Miquelon"),
  PN("Pitcairn", "Pitcairn"),
  PR("Puerto Rico", "Puerto Rico"),
  PS("Palestinian Territories", "Palestine, State of"),
  PT("Portugal", "Portugal"),
  PW("Palau", "Palau"),
  PY("Paraguay", "Paraguay"),
  QA("Qatar", "Qatar"),
  RE("Réunion", "Réunion"),
  RO("Romania", "Romania"),
  RS("Serbia", "Serbia"),
  RU("Russia", "Russian Federation (the)"),
  RW("Rwanda", "Rwanda"),
  SA("Saudi Arabia", "Saudi Arabia"),
  SB("Solomon Islands", "Solomon Islands"),
  SC("Seychelles", "Seychelles"),
  SD("Sudan", "Sudan (the)"),
  SE("Sweden", "Sweden"),
  SG("Singapore", "Singapore"),
  SH(
      "Saint Helena, Ascension and Tristan da Cunha",
      "Saint Helena, Ascension and Tristan da Cunha"),
  SI("Slovenia", "Slovenia"),
  SJ("Svalbard and Jan Mayen", "Svalbard and Jan Mayen"),
  SK("Slovakia", "Slovakia"),
  SL("Sierra Leone", "Sierra Leone"),
  SM("San Marino", "San Marino"),
  SN("Senegal", "Senegal"),
  SO("Somalia", "Somalia"),
  SR("Suriname", "Suriname"),
  SS("South Sudan", "South Sudan"),
  ST("São Tomé and Príncipe", "Sao Tome and Principe"),
  SV("El Salvador", "El Salvador"),
  SX("Sint Maarten (Netherlands)", "Sint Maarten (Dutch part)"),
  SY("Syria", "Syrian Arab Republic"),
  SZ("Eswatini", "Eswatini"),
  TC("Turks and Caicos Islands", "Turks and Caicos Islands (the)"),
  TD("Chad", "Chad"),
  TF("French Southern Territories", "French Southern Territories (the)"),
  TG("Togo", "Togo"),
  TH("Thailand", "Thailand"),
  TJ("Tajikistan", "Tajikistan"),
  TK("Tokelau", "Tokelau"),
  TL("East Timor", "Timor-Leste"),
  TM("Turkmenistan", "Turkmenistan"),
  TN("Tunisia", "Tunisia"),
  TO("Tonga", "Tonga"),
  TR("Turkey", "Turkey"),
  TT("Trinidad and Tobago", "Trinidad and Tobago"),
  TV("Tuvalu", "Tuvalu"),
  TW("Taiwan", "Taiwan"),
  TZ("Tanzania", "Tanzania, United Republic of"),
  UA("Ukraine", "Ukraine"),
  UG("Uganda", "Uganda"),
  UM("United States Minor Outlying Islands", "United States Minor Outlying Islands (the)"),
  US("United States of America", "United States of America (the)"),
  UY("Uruguay", "Uruguay"),
  UZ("Uzbekistan", "Uzbekistan"),
  VA("Vatican City", "Holy See (the)"),
  VC("Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines"),
  VE("Venezuela", "Venezuela (Bolivarian Republic of)"),
  VG("British Virgin Islands", "Virgin Islands (British)"),
  VI("United States Virgin Islands", "Virgin Islands (U.S.)"),
  VN("Vietnam", "Viet Nam"),
  VU("Vanuatu", "Vanuatu"),
  WF("Wallis and Futuna", "Wallis and Futuna"),
  WS("Sāmoa", "Samoa"),
  YE("Yemen", "Yemen"),
  YT("Mayotte", "Mayotte"),
  ZA("South Africa", "South Africa"),
  ZM("Zambia", "Zambia"),
  ZW("Zimbabwe", "Zimbabwe");

  companion object {

    /** Case-sensitive search for a given country name */
    fun fromCountryName(countryName: String) =
        values().firstOrNull { it.countryName == countryName }

    /**
     * true, if a country exists with the given name. The comparison respects the case; a country
     * given in lower case will not be found.
     */
    fun fromCountryNameExists(countryName: String) =
        values().map { it.countryName }.contains(countryName)

    /** Case-sensitive search for a given alternative country name */
    fun fromAlternativeCountryName(alternativeCountryName: String) =
        values().firstOrNull { it.alternativeCountryName == alternativeCountryName }

    /**
     * true, if a country exists with the given alternative name. The comparison respects the case;
     * a country given in lower case will not be found.
     */
    fun fromAlternativeCountryNameExists(alternativeCountryName: String) =
        values().map { it.alternativeCountryName }.contains(alternativeCountryName)

    /**
     * Case-insensitive search for a given two-letter country code (in lower, upper, or mixed case)
     */
    fun fromCountryCode(countryCode: String) =
        values().firstOrNull { it.name == countryCode.uppercase() }
  }
}
