package com.bosch.pt.csm.cloud.job.common.translation
// ---------------------------------
// WARNING: Generated by Gradle task - NOT TO BE EDITED
// ---------------------------------

object Key {

    /**
     * en
     */
    const val KEY = "Key"

    /**
     * The requested Job was not found.
     */
    const val JOB_VALIDATION_ERROR_NOT_FOUND = "Job_ValidationError_NotFound"

    /**
     * Only completed Jobs can be marked as read.
     */
    const val JOB_VALIDATION_ERROR_ONLY_COMPLETED_JOBS_CAN_BE_MARKED_AS_READ = "Job_ValidationError_OnlyCompletedJobsCanBeMarkedAsRead"

    /**
     * The requested Job state transition is not possible.
     */
    const val JOB_VALIDATION_ERROR_INVALID_JOB_STATE_TRANSITION = "Job_ValidationError_InvalidJobStateTransition"

}
