info:
  app:
    name: ${spring.application.name}

spring:
  config:
    import:
      - classpath:actuator-common.yml
      - classpath:apiversion.yml
      - classpath:flyway.yml
      - classpath:kafka.yml
      - classpath:logging.yml
      - classpath:metrics-common.yml
      - classpath:mysql.yml
      - classpath:profiles.yml
      - classpath:server.yml
      - classpath:topics.yml
  cloud:
    loadbalancer:
      cache:
        enabled: false
  jackson:
    default-property-inclusion: non_null
  jmx:
    enabled: true # enable jmx to get kafka metrics via micrometer
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physicalNamingStrategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        order_inserts: true
        order_updates: true
        #log sql statements
        # show_sql: true
        # format_sql: true
      jdbc:
        batch_size: 100
    open-in-view: false
  messages:
    basename: i18n/messages
    encoding: UTF-8
  threads:
    virtual:
      enabled: true

custom:
  business-transaction:
    consumer:
      persistence: jpa

db:
  in:
    max-size: 1000

locale:
  default: en_GB
  supported: en_GB, de_DE, es_ES, pt_PT, fr_FR

---
spring:
  config:
    activate:
      on-profile: kubernetes

custom:
  process-state-only:
    enabled: ${process-state-only-enabled}
    until-date: ${process-state-only-until-date}

---
spring:
  config:
    activate:
      on-profile: local

custom:
  swagger:
    url: /

stage: local

---
spring:
  config:
    activate:
      on-profile: swagger

springdoc:
  api-docs:
    enabled: true
    path: /swagger/news/api-definition
  writer-with-order-by-keys: true
