# Environment specific values for csm-cloud-project-notifications.
# Declare variables to be passed into your templates.

stage: prod
profiles: production, idp-bosch-prod, notify-user-registrations
livenessProbeInitialDelay: 30

# configuration for KV Flex volumes
env: prod
subscription: prod
subscriptionid: "REPLACE_ME"
tenantid: "REPLACE_ME"
