kafka:
  broker:
    address:
      family: v4
    urls: localhost:9092
  schemaRegistry:
    urls: http://localhost:8081
  schema:
    autoRegisterSchemas: true
  topic:
    autoCreateTopics: true
    upload:
      name: csm.local.storage.event
      replicationFactor: 1

server:
  port: 9040

storage:
  queueName: csm-quarantine-queue
  connectionString: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1;QueueEndpoint=http://localhost:10001/devstoreaccount1
  queuePollingInterval: 3s