/*
 * ************************************************************************
 *
 *  Copyright:       Robert Bosch Power Tools GmbH, 2018 - 2021
 *
 * ************************************************************************
 */

package com.bosch.pt.csm.cloud.projectmanagement.common

enum class ProjectmanagementAggregateTypeEnum(val value: String) {
  DAYCARD("DAYCARD"),
  EXTERNAL_ID("EXTERNAL_ID"),
  INVITATION("INVITATION"),
  MESSAGE("MESSAGE"),
  MESSAGEATTACHMENT("MESSAGEATTACHMENT"),
  MILESTONE("MILESTONE"),
  MILESTONELIST("MILESTONELIST"),
  PARTICIPANT("PARTICIPANT"),
  PROJECT("PROJECT"),
  PROJECTCRAFT("PROJECTCRAFT"),
  PROJECTCRAFTLIST("PROJECTCRAFTLIST"),
  PROJECTPICTURE("PROJECTPICTURE"),
  RELATION("RELATION"),
  RFVCUSTOMIZATION("RFVCUSTOMIZATION"),
  TASK("TASK"),
  TASKACTION("TASKACTION"),
  TASKATTACHMENT("TASKATTACHMENT"),
  TASKCONSTRAINTCUSTOMIZATION("TASKCONSTRAINTCUSTOMIZATION"),
  TASKSCHEDULE("TASKSCHEDULE"),
  TOPIC("TOPIC"),
  TOPICATTACHMENT("TOPICATTACHMENT"),
  WORKAREA("WORKAREA"),
  WORKAREALIST("WORKAREALIST"),
  WORKDAYCONFIGURATION("WORKDAYCONFIGURATION")
}
