# Environment specific values for csm-cloud-storage-event-core.
# Declare variables to be passed into your templates.

stage: prod
profiles: production, kubernetes

# configuration for KV Flex volumes
env: prod
subscription: prod
subscriptionid: "REPLACE_ME"
tenantid: "REPLACE_ME"
