package com.bosch.pt.csm.cloud.common.translation
// ---------------------------------
// WARNING: Generated by Gradle task - NOT TO BE EDITED
// ---------------------------------

object CommonStreamableKey {

    /**
     * en
     */
    const val KEY = "Key"

    /**
     * Record can not be updated because the provided version is outdated.
     */
    const val COMMON_VALIDATION_ERROR_ENTITY_OUTDATED = "Common_ValidationError_EntityOutdated"

}
