# Environment specific values for csm-cloud-project.
# Declare variables to be passed into your templates.

stage: prod
profiles: production, idp-bosch-prod
domainName: app.bosch-refinemysite.com
domainNameApi: api.bosch-refinemysite.com
livenessProbeInitialDelay: 240

mailjetBccEmail: support.refinemysite@de.bosch.com
mailjetErrorReportingEmail: monitoring-prod-aaaabfcbeb2qofn5uwzkp26anm@smartsite-nt-bpt.slack.com

# configuration for KV Flex volumes
env: prod
subscription: prod
subscriptionid: "d758dda6-675e-47a2-b269-866d5e4f918f"
tenantid: "0ae51e19-07c8-4e4b-bb6d-648ee58410f4"
