apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Chart.Name }}-sub-aks-kv"
spec:
  provider: azure
  parameters:
    keyvaultName: "ptcsm{{ .Values.subscription  }}subakskv"
    objects: |
      array:
        - |
          objectName: csm-app-admin-password
          objectType: secret
        - |
          objectName: csm-app-admin-user
          objectType: secret
        - |
          objectName: csm-cloud-reset-storage-account-connection-string
          objectType: secret
        - |
          objectName: skid-captcha-bypass-client-id
          objectType: secret
        - |
          objectName: skid-captcha-bypass-client-secret
          objectType: secret
    resourceGroup: "pt-csm-{{ .Values.subscription }}-sub-aks-kv"
    subscriptionId: {{ quote .Values.subscriptionid }}
    tenantId: {{ quote .Values.tenantid }}
