apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Chart.Name }}-env-aks-kv"
spec:
  provider: azure
  parameters:
    keyvaultName: "ptcsm{{ .Values.env }}envakskv"
    objects: |
      array:
        - |
          objectName: csm-cloud-company-mysql-flexible-url
          objectType: secret
        - |
          objectName: csm-cloud-featuretoggle-mysql-flexible-url
          objectType: secret
        - |
          objectName: csm-cloud-project-mysql-flexible-url
          objectType: secret
        - |
          objectName: csm-cloud-project-news-mysql-flexible-url
          objectType: secret
        - |
          objectName: csm-cloud-project-statistics-mysql-flexible-url
          objectType: secret
        - |
          objectName: csm-cloud-user-mysql-flexible-url
          objectType: secret
        {{- if .Values.company.restore.secret.enabled }}
        - |
          objectName: csm-cloud-company-restore-mysql-flexible-url
          objectType: secret
        {{- end }}
        {{- if .Values.project.restore.secret.enabled }}
        - |
          objectName: csm-cloud-project-restore-mysql-flexible-url
          objectType: secret
        {{- end }}
        {{- if .Values.user.restore.secret.enabled }}
        - |
          objectName: csm-cloud-user-restore-mysql-flexible-url
          objectType: secret
        {{- end }}
        - |
          objectName: csm-cloud-project-activity-mongodbatlas-connection-string
          objectType: secret
        - |
          objectName: csm-cloud-project-api-timeseries-mongodbatlas-connection-string
          objectType: secret
        - |
          objectName: csm-cloud-project-mongodbatlas-connection-string
          objectType: secret
        - |
          objectName: csm-cloud-project-notification-mongodbatlas-connection-string
          objectType: secret
        - |
          objectName: csm-cloud-job-mongodbatlas-connection-string
          objectType: secret
        - |
          objectName: csm-cloud-project-storage-account-connection-string
          objectType: secret
        - |
          objectName: csm-cloud-project-downloads-storage-account-connection-string
          objectType: secret
        - |
          objectName: csm-cloud-user-storage-account-connection-string
          objectType: secret
        - |
          objectName: csm-cloud-reset-kafka-broker-api-key
          objectType: secret
        - |
          objectName: csm-cloud-reset-kafka-broker-api-secret
          objectType: secret
        - |
          objectName: csm-monitoring-event-postgresql-flexible-url
          objectType: secret
        - |
          objectName: kafka-broker-urls
          objectType: secret
        - |
          objectName: kafka-schemaregistry-api-key
          objectType: secret
        - |
          objectName: kafka-schemaregistry-api-secret
          objectType: secret
        - |
          objectName: kafka-schemaregistry-urls
          objectType: secret
        - |
          objectName: kafka-topic-company
          objectType: secret
        - |
          objectName: kafka-topic-consents
          objectType: secret
        - |
          objectName: kafka-topic-craft
          objectType: secret
        - |
          objectName: kafka-topic-event
          objectType: secret
        - |
          objectName: kafka-topic-featuretoggle
          objectType: secret
        - |
          objectName: kafka-topic-image-scale
          objectType: secret
        - |
          objectName: kafka-topic-pat
          objectType: secret
        - |
          objectName: kafka-topic-project
          objectType: secret
        - |
          objectName: kafka-topic-project-delete
          objectType: secret
        - |
          objectName: kafka-topic-project-invitation
          objectType: secret
        - |
          objectName: kafka-topic-storage-event
          objectType: secret
        - |
          objectName: kafka-topic-user
          objectType: secret
        - |
          objectName: kafka-topic-job-event
          objectType: secret
        - |
          objectName: kafka-topic-job-command
          objectType: secret
    resourceGroup: "pt-csm-{{ .Values.env }}-env-aks-kv"
    subscriptionId: {{ quote .Values.subscriptionid }}
    tenantId: {{ quote .Values.tenantid }}
