info:
  app:
    name: ${spring.application.name}

spring:
  config:
    import:
      - classpath:actuator-common.yml
      - classpath:apiversion.yml
      - classpath:blobstorage.yml
      - classpath:flyway.yml
      - classpath:kafka.yml
      - classpath:logging.yml
      - classpath:metrics-common.yml
      - classpath:mysql.yml
      - classpath:profiles.yml
      - classpath:server.yml
      - classpath:skid.yml
      - classpath:topics.yml
  cloud:
    loadbalancer:
      cache:
        enabled: false
  aop:
    auto: true
  cache:
    jcache:
      config: classpath:ehcache.xml
  data:
    web:
      pageable:
        max-page-size: 100
        default-page-size: 20
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        order_inserts: true
        order_updates: true
        #log sql statements
        #show_sql: true
        #format_sql: true
      jdbc:
        batch_size: 100
    open-in-view: false
  messages:
    basename: i18n/messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 20MB
      # The max request size is larger than the max file size to cater for the "overhead" the http header produces
      max-request-size: 21MB
    scheduled:
      skipPattern: com.bosch.pt.csm.cloud.usermanagement.attachment.facade.listener.ImageScalingListener
  threads:
    virtual:
      enabled: true

attachment:
  image:
    resolution:
      # 2 mega pixel
      max: 2000000
    thumbnail:
      resolution:
        # 196px x 196 px
        max: 38416

custom:
  scheduling:
    enabled: true

locale:
  default: en_GB
  supported: en_GB, de_DE, es_ES, pt_PT, fr_FR

db:
  in:
    max-size: 1000

system:
  user:
    identifier: c37da613-8e70-4003-9106-12412c9d2496

---
spring:
  config:
    activate:
      on-profile: local

custom:
  swagger:
    url: /

stage: local

---
spring:
  config:
    activate:
      on-profile: swagger

springdoc:
  api-docs:
    enabled: true
    path: /swagger/users/api-definition
  writer-with-order-by-keys: true
