info:
  app:
    name: ${spring.application.name}

spring:
  config:
    import:
      - classpath:actuator-common.yml
      - classpath:apiversion.yml
      - classpath:blobstorage.yml
      - classpath:flyway.yml
      - classpath:kafka.yml
      - classpath:listeners.yml
      - classpath:logging.yml
      - classpath:mailjet.yml
      - classpath:metrics-common.yml
      - classpath:mongodb.yml
      - classpath:mysql.yml
      - classpath:profiles.yml
      - classpath:server.yml
      - classpath:topics.yml
  cloud:
    loadbalancer:
      cache:
        enabled: false
  aop:
    auto: true
  cache:
    type: simple
  data:
    web:
      pageable:
        max-page-size: 500
        default-page-size: 20
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        order_inserts: true
        order_updates: true
        #log sql statements
        #show_sql: true
        #format_sql: true
      jdbc:
        batch_size: 100
    open-in-view: false
  messages:
    basename: i18n/messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 200MB
      # The max request size is larger then the max file size to cater for the "overhead" the http header produces when the file itself is already 5 MB
      max-request-size: 201MB
  threads:
    virtual:
      enabled: true

custom:
  business-transaction:
    consumer:
      persistence: jpa
  feature.enabled: true

attachment:
  image:
    resolution:
      # 2 mega pixel
      max: 2000000
    thumbnail:
      resolution:
        # 196px x 196 px
        max: 38416

locale:
  default: en_GB
  supported: en_GB, de_DE, es_ES, pt_PT, fr_FR

db:
  in:
    max-size: 1000

system:
  user:
    identifier: c37da613-8e70-4003-9106-12412c9d2496

---
spring:
  config:
    activate:
      on-profile: local

custom:
  swagger:
    url: /

csm.pdf.url: http://localhost:8082
csm.project.url: http://localhost:8080
# To run the pdf converter in the docker container use this callback url:
#csm.project.url: http://172.17.0.1:8080

stage: local

---
spring:
  config:
    activate:
      on-profile: swagger

springdoc:
  api-docs:
    enabled: true
    path: /swagger/projects/api-definition
  writer-with-order-by-keys: true
