/*
 * ************************************************************************
 *
 *  Copyright:       Robert Bosch Power Tools GmbH, 2018 - 2021
 *
 * ************************************************************************
 */
package com.bosch.pt.csm.cloud.projectmanagement.statistics.model

/**
 * A day card has a reason for not being done, but the statistic will deliver a "reason for
 * variance" that will also include day cards still open without a reason for not being done. So
 * this is enum is more like a union of [DayCardReasonNotDoneEnum] and an additional state of being
 * still "open"
 */
enum class DayCardReasonVarianceEnum {
  DELAYED_MATERIAL,
  NO_CONCESSION,
  CONCESSION_NOT_RECOGNIZED,
  CHANGED_PRIORITY,
  MANPOWER_SHORTAGE,
  OVERESTIMATION,
  TOUCHUP,
  MISSING_INFOS,
  MISSING_TOOLS,
  BAD_WEATHER,
  OTHER,
  CUSTOM1,
  CUSTOM2,
  CUSTOM3,
  CUSTOM4,

  /** it will only be generated by day cards that are still open */
  OPEN;

  fun isCustom() = this == CUSTOM1 || this == CUSTOM2 || this == CUSTOM3 || this == CUSTOM4
}
