spring:
  profiles:
    group:
      local:
        - idp-bosch-dev
        - init-topics
      staging:
        - idp-bosch-dev
        - init-topics
        - kubernetes
        - log-json
      production:
        # - idp-bosch-prod (controlled by helm chart since production profile is used on review, too
        - kubernetes
        - log-json

# restore-db: Additional profile used when application should start in restore mode
# log-jpa: Additional profile used for additional jpa logging output