server:
  servlet:
    context-path:
  shutdown: graceful

---
spring:
  config:
    activate:
      on-profile: local

custom:
  shutdown:
    timeout-seconds: 0

server:
  port: 8020
  shutdown: immediate
