custom:
  kafka:
    bindings:
      event:
        configuration:
          properties:
            # 10 minutes
            retention.ms: 600000
---
spring:
  config:
    activate:
      on-profile: kubernetes

custom:
  kafka:
    bindings:
      event:
        kafkaTopic: ${kafka-topic-event}

---
spring:
  config:
    activate:
      on-profile: staging

custom:
  kafka:
    bindings:
      event:
        configuration:
          partitions: 2
          properties:
            min.insync.replicas: 2

---
spring:
  config:
    activate:
      on-profile: production

custom:
  kafka:
    bindings:
      event:
        configuration:
          partitions: 6
          properties:
            min.insync.replicas: 2

---
spring:
  config:
    activate:
      on-profile: local || test

custom:
  kafka:
    bindings:
      event:
        kafkaTopic: "csm.local.event"
        configuration:
          # The local kafka cluster has only one broker node at the moment.
          replication: 1
          properties:
            min.insync.replicas: 1