info:
  app:
    name: ${spring.application.name}

locale:
  default: en_GB
  supported: en_GB, de_DE, es_ES, pt_PT, fr_FR

spring:
  config:
    import:
      - classpath:actuator-common.yml
      - classpath:apiversion.yml
      - classpath:kafka.yml
      - classpath:listeners.yml
      - classpath:logging.yml
      - classpath:metrics-common.yml
      - classpath:mongodb.yml
      - classpath:profiles.yml
      - classpath:server.yml
      - classpath:topics.yml
  cloud:
    loadbalancer:
      cache:
        enabled: false
  cache:
    jcache:
      config: classpath:ehcache.xml
  graphql:
    graphiql:
      enabled: true
  jackson:
    default-property-inclusion: non_null
  jmx:
    enabled: true # enable jmx to get kafka metrics via micrometer
  messages:
    basename: i18n/messages
    encoding: UTF-8
  threads:
    virtual:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /swagger/timeline/api-definition
  writer-with-order-by-keys: true

---
spring:
  config:
    activate:
      on-profile: local

stage: local