package com.bosch.pt.csm.cloud.common.translation
// ---------------------------------
// WARNING: Generated by Gradle task - NOT TO BE EDITED
// ---------------------------------

object Key {

    /**
     * en
     */
    const val KEY = "Key"

    /**
     * Change of record not possible as record was already updated or deleted by another user.
     */
    const val COMMON_VALIDATION_ERROR_OPTIMISTIC_LOCKING = "Common_ValidationError_OptimisticLocking"

    /**
     * Creation or modification of the record is not possible because specified data of record violates integrity constraints.
     */
    const val COMMON_VALIDATION_ERROR_DATA_INTEGRITY_VIOLATED = "Common_ValidationError_DataIntegrityViolated"

    /**
     * Creation of feature toggle is not possible as a feature with the name exists already.
     */
    const val FEATURE_TOGGLE_VALIDATION_ERROR_FEATURE_ALREADY_EXISTS = "FeatureToggle_ValidationError_FeatureAlreadyExists"

    /**
     * The feature does not exist
     */
    const val FEATURE_TOGGLE_VALIDATION_ERROR_FEATURE_NOT_FOUND = "FeatureToggle_ValidationError_FeatureNotFound"

    /**
     * The subject is already in the feature whitelist
     */
    const val FEATURE_TOGGLE_VALIDATION_ERROR_SUBJECT_WHITELISTED_ALREADY = "FeatureToggle_ValidationError_SubjectWhitelistedAlready"

    /**
     * The subject is not present in the feature whitelist
     */
    const val FEATURE_TOGGLE_VALIDATION_ERROR_SUBJECT_NOT_FOUND_IN_WHITELIST = "FeatureToggle_ValidationError_SubjectNotFoundInWhitelist"

}
