apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Chart.Name }}-env-aks-kv"
spec:
  provider: azure
  parameters:
    keyvaultName: "ptcsm{{ .Values.env }}envakskv"
    objects: |
      array:
        - |
          objectName: csm-cloud-api-mongodbatlas-connection-string
          objectType: secret
    resourceGroup: "pt-csm-{{ .Values.env }}-env-aks-kv"
    subscriptionId: {{ quote .Values.subscriptionid }}
    tenantId: {{ quote .Values.tenantid }}
